openapi: 3.0.0
info:
  version: 0.0-oas3
  title: coviddataprojection
  description: >-
    Service to get the projected number of covid cases in the user's area for the next day
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Cloudmesh REST Service Example
  license:
    name: Apache
paths:
  /covidprojection/{locations}:
    get:
      tags:
        - Covid19
        - Projection
      operationId: ML_Project3.predict_data
      description: Returns predicted number of Covid19 cases in a given region(s) over a given number of days
      parameters:
        - in: path
          name: locations
          required: true
          schema:
            type: array
            items:
              type: string
            minItems: 1
          style: simple
          explode: true
        - in: query
          name: days
          required: false
          schema:
            type: integer
          description: 'Number of days out to predict'
      responses:
        '200':
          description: 'Prediction for Selected Region:'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prediction'
servers:
  - url: 'http://localhost:8080/ml_application'
components:
  schemas:
    Prediction:
      type: object
      required:
        - model
        - prediction
      properties:
        model:
          type: string
        prediction:
          type: string