openapi: 3.0.0
info:
  version: 0.0-oas3
  title: coviddataprojection
  description: >-
    Service to get the likelihood that a hotel room booking will be cancelled.
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Cloudmesh REST Service Example
  license:
    name: Apache
paths:
  /predict/{id}:
    get:
      tags:
        - PRED
      operationId: prediction.my_prediction
      description: Booking Cancellation Predictor
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: array
            items:
              type: number
            minItems: 1
          style: simple
          explode: true
        - in: query
          name: metadata
          schema:
            type: boolean
      responses:
        '200':
          description: 'Booking Cancellation Predictor'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CPU'
servers:
  - url: 'http://localhost:8080/ml_application'
components:
  schemas:
    CPU:
      type: object
      required:
        - model
      properties:
        model:
          type: string
    OS:
      type: object
      required:
        - model
      properties:
        model:
          type: string